# Configuration for the GitHub Actions labeler
# Labels by affected paths

core:
  - src/**/core/*
blocks:
  - src/**/block/*
items:
  - src/**/item/*
entities:
  - src/**/entity/*
tile-entities:
  - src/**/tileentity/*
networking:
  - src/**/network/*
particles:
  - src/**/particle/*
rituals:
  - src/**/ritual/*
