#Configuration for the pullRequestLabeler action.

#Path configurations
#Modules
1.7.10: ['*/1.7.10/*']
1.12.2: ['*/1.12.2/*']
1.15.2: ['*/1.15.2/*']
1.16.4: ['*/1.16.4/*']
feature: ['feature/*']
bug: ['bug/*']
