modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL 3"
issueTrackerURL="https://github.com/GenElectrovise/MagiksMostEvile/issues"
[[mods]]
modId="magiksmostevile"
version="${file.jarVersion}"
displayName="Magiks Most Evile"
#updateJSONURL="http://example.net/"
displayURL="https://github.com/GenElectrovise/MagiksMostEvile/"
logoFile="magiksmostevile.png"
credits="All credit to Flappy.                        And no others."
authors="GenElectrovise"
description='''
Makes Minecraft a bit more evile and a lot more magiky.
'''
[[dependencies.magiksmostevile]]
    modId="forge" 
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.magiksmostevile]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
