modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL 3"
issueTrackerURL="https://github.com/GenElectrovise/MagiksMostEvile/issues"
[[mods]]
modId="magiksmostevile"
version="${file.jarVersion}"
displayName="Magiks Most Evile"
#updateJSONURL="http://example.net/"
displayURL="https://github.com/GenElectrovise/MagiksMostEvile/"
logoFile="magiksmostevile.png"
credits="All credit to Flappy.                        And no others." #optional
authors="GenElectrovise"
description='''
Makes Minecraft a bit more evile and a lot more magiky.
'''
[[dependencies.magiksmostevile]] #optional
    modId="forge" 
    mandatory=true
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.magiksmostevile]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"